//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gazprom2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GasEquipment_User
    {
        public int idUser { get; set; }
        public int idGasEquipment { get; set; }
    
        public virtual GasEquipment GasEquipment { get; set; }
        public virtual User User { get; set; }
    }
}
