//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gazprom2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GasEquipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GasEquipment()
        {
            this.GasEquipment_User = new HashSet<GasEquipment_User>();
            this.MaintenanceOfGasEquipment = new HashSet<MaintenanceOfGasEquipment>();
        }
    
        public int id { get; set; }
        public string GasEquipmentName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GasEquipment_User> GasEquipment_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceOfGasEquipment> MaintenanceOfGasEquipment { get; set; }
    }
}
