//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gazprom2.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gazprom2Entities : DbContext
    {
        public Gazprom2Entities()
            : base("name=Gazprom2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationForGasConnection> ApplicationForGasConnection { get; set; }
        public virtual DbSet<ApplicationStatus> ApplicationStatus { get; set; }
        public virtual DbSet<GasEquipment> GasEquipment { get; set; }
        public virtual DbSet<GasSupplyMethods> GasSupplyMethods { get; set; }
        public virtual DbSet<MaintenanceOfGasEquipment> MaintenanceOfGasEquipment { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<GasEquipment_User> GasEquipment_User { get; set; }
    }
}
