//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gazprom2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ApplicationForGasConnection = new HashSet<ApplicationForGasConnection>();
            this.MaintenanceOfGasEquipment = new HashSet<MaintenanceOfGasEquipment>();
            this.GasEquipment_User = new HashSet<GasEquipment_User>();
        }
    
        public int id { get; set; }
        public int idRole { get; set; }
        public string fullName { get; set; }
        public System.DateTime dateOfBrith { get; set; }
        public double passportSeries { get; set; }
        public double passportNumber { get; set; }
        public string phoneNumber { get; set; }
        public string eMail { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationForGasConnection> ApplicationForGasConnection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceOfGasEquipment> MaintenanceOfGasEquipment { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GasEquipment_User> GasEquipment_User { get; set; }
    }
}
