//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gazprom2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int id { get; set; }
        public int idRole { get; set; }
        public string fullName { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
